# .github/workflows/your-workflow-name.yml
name: Build, Test, and Deploy to GitHub Pages

on:
  push:
    paths:
      - 'src/**'
      - 'tests/**'
      - '.github/**'
      - '*.ts'
      - '*.tsx'
      - '*.css'
      - '*.html'
      - '*.json'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
  contents: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install dependencies
        run: npm ci

      - name: Set up base path for deployment
        run: |
          if [ "${{ github.ref_name }}" = "main" ]; then
            echo "VITE_BASE_PATH=/autism-wheel/" >> $GITHUB_ENV
          else
            echo "VITE_BASE_PATH=/autism-wheel/branch/${{ github.ref_name }}/" >> $GITHUB_ENV
          fi

      - name: Build project
        run: npm run build
        env:
          VITE_BASE_PATH: ${{ env.VITE_BASE_PATH }}

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: build/

  test:
    runs-on: ubuntu-latest
    needs: [build]  # Wait for build to complete first
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Cache Playwright browsers
        id: cache-playwright
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Install dependencies
        run: npm ci

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: build/

      - name: Verify build files
        run: |
          echo "Checking build directory contents:"
          ls -la build/
          if [ ! -f "build/index.html" ]; then
            echo "Error: build/index.html not found!"
            exit 1
          fi
          echo "Build verification successful!"

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npm test
        env:
          CI: true
  deploy-main:
    runs-on: ubuntu-latest
    if: github.ref_name == 'main'
    needs: [build, test]  # Wait for both build AND test to complete successfully
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: build/
      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          keep_files: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Deploy from ${{ github.sha }}'

  deploy-feature:
    runs-on: ubuntu-latest
    if: github.ref_name != 'main'
    needs: [build]  # Only wait for build, NOT tests
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: build/
      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          destination_dir: ./branch/${{ github.ref_name }}
          keep_files: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Deploy from ${{ github.sha }}'
