# .github/workflows/your-workflow-name.yml
name: Build, Test, and Deploy to GitHub Pages

on:
  # Runs on pushes to any branch
  push:
    paths:
      - 'src/**'
      - '.github/**'
      - '*.ts'
      - '*.tsx'
      - '*.css'
      - '*.html'
      - '*.json'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write # Needed to push to the gh-pages branch

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install dependencies
        run: npm ci

      - name: Set up base path for deployment
        run: |
          if [ "${{ github.ref_name }}" = "main" ]; then
            echo "VITE_BASE_PATH=/autism-wheel/" >> $GITHUB_ENV
          else
            echo "VITE_BASE_PATH=/autism-wheel/branch/${{ github.ref_name }}/" >> $GITHUB_ENV
          fi

      - name: Build project
        run: npm run build
        env:
          VITE_BASE_PATH: ${{ env.VITE_BASE_PATH }}

      # This single step replaces 'playwright install', 'serve', and 'npm test'
      - name: Run Playwright tests
        uses: microsoft/playwright-github-action@v1
        with:
          # The command to run your tests
          run: npm test
          # The command to build your app (already done, but good practice to have)
          build: npm run build
          # The command to start a preview server
          start: npm install -g serve && serve -s build -l 3000

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: build/

  deploy-main:
    runs-on: ubuntu-latest
    if: github.ref_name == 'main'
    # Now only needs the single 'build-and-test' job
    needs: [build-and-test]
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: build/
      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          keep_files: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Deploy from ${{ github.sha }}'

  deploy-feature:
    runs-on: ubuntu-latest
    if: github.ref_name != 'main'
    # Now only needs the single 'build-and-test' job
    needs: [build-and-test]
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: build/
      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          destination_dir: ./branch/${{ github.ref_name }}
          keep_files: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Deploy from ${{ github.sha }}'
